description: Let ChatGPT suggest commit messages.
name: gpt_commit_messages
repository: https://github.com/Goddchen/gpt-commit-messages
version: 0.2.0

dependencies:
  args: ^2.4.0
  fpdart: ^0.5.0
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  logger: ^1.3.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lints: ^2.0.0
  test: ^1.21.0

environment:
  sdk: ">=2.19.2 <3.0.0"

executables:
  gpt-commit-messages: gpt_commit_messages
